config/routes.rb
Rails.application.routes.draw do
  resources :reservations
  #get 'flights#index'
  root to: "home#index"

  resources :flights

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :reservations
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  require 'pagy/extras/array'
  before_action :set_flight, only: %i[ show edit update destroy ]

  # GET /flights or /flights.json
  def index
    #@pagy, @flights = pagy(Flight.all)
    @pagy, @flights = pagy_array(Flight.all.select{ |v| v.departure_date.future? }.to_ary, item: 5)
  end

  # GET /flights/1 or /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights or /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: "Flight was successfully created." }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1 or /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: "Flight was successfully updated." }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1 or /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: "Flight was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_flight
    @flight = Flight.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def flight_params
    params.require(:flight).permit(:number, :departure_airport, :arrival_airport, :business_class_seats, :economy_class_seats, :duration, :departure_date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @flight = Flight.find(params[:flight_id])
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user

    respond_to do |format|
      if @reservation.save

        ReservationMailer.confirm_mail(@reservation.user, @reservation).deliver_now

        format.html { redirect_to @reservation, notice: "Reservation was successfully created." }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  # Only allow a list of trusted parameters through.
  def reservation_params
    # params.fetch(:reservation, {})
    params.require(:reservation).permit(:created_at, :updated_at, :flight_id, :user_id, :class_seats, :code_reservation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/flight_helper.rb
module FlightHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/flights/_form.html.erb
<%= form_with(model: flight) do |form| %>
  <% if flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
        <% flight.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field form-group">
    <label><%= form.label :number %></label>
    <%= form.number_field :number, class:'form-control col-md-4 offset-md-4', style:'text-align: center' %>
  </div>

  <div class="field form-group">
    <%= form.label :departure_airport %>
    <%= form.text_field :departure_airport, class:'form-control col-md-4 offset-md-4', style:'text-align: center' %>
  </div>

  <div class="field form-group">
    <%= form.label :arrival_airport %>
    <%= form.text_field :arrival_airport, class:'form-control col-md-4 offset-md-4', style:'text-align: center' %>
  </div>

  <div class="field form-group">
    <%= form.label :business_class_seats %>
    <%= form.number_field :business_class_seats,class:'form-control col-md-4 offset-md-4', style:'text-align: center' %>
  </div>

  <div class="field form-group">
    <%= form.label :economy_class_seats %>
    <%= form.number_field :economy_class_seats, class:'form-control col-md-4 offset-md-4', style:'text-align: center'%>
  </div>

  <div class="field form-group">
    <%= form.label :duration %>
    <%= form.number_field :duration, class:'form-control col-md-4 offset-md-4', style:'text-align: center'%>
  </div>

  <div class="field form-group">
    <%= form.label :departure_date , class:'form-label'%>
    <%= form.datetime_select :departure_date , class:'form-control col-md-4 offset-md-4', style:'text-align: center'%>
  </div>

  <div class="actions">
    <%= form.submit 'Envoyer', class:'btn btn-success'%>
  </div>
<% end %>

app/views/flights/edit.html.erb
<div style="text-align: center">
  <h1>Editing Flight</h1>
  <%= render 'form', flight: @flight %>
  <%= link_to 'Show', @flight %> |
  <%= link_to 'Back', flights_path %>
</div>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center; margin-bottom: 30px;">Flights</h1>

<div class="table-responsive">
    <table class="table" style="text-align: center">
      <thead>
        <tr>
          <th scope="col">Number</th>
          <th scope="col">Departure airport</th>
          <th scope="col">Arrival airport</th>
          <th scope="col">Departure date</th>
          <th scope="col">Arrival date</th>
          <th scope="col" colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.number %></td>
          <td><%= flight.departure_airport %></td>
          <td><%= flight.arrival_airport %></td>
          <td><%= flight.departure_date.strftime("%d/%m/%Y à %H:%M") %></td>
         <!-- <td><#%= (flight.departure_date + flight.duration*60).strftime("%d/%m/%Y à %H:%M") %></td>-->
          <td>
            <!--<%#= link_to 'Show', flight %>-->
            <%= link_to flight_path(flight.id) do %><i class="bi bi-eye" title="SHOW">SHOW</i><% end %>
          </td>

          <td>
            <!--<%#= link_to 'Edit', edit_flight_path(flight) %>-->
            <%= link_to edit_flight_path(flight) do %><i class="bi bi-pencil" style="color:dodgerblue;" title="EDIT">Edit</i><% end %>
          </td>

          <td>
    <!--        <%#= link_to edit_flight_path(flight) do %><i class="bi bi-trash"></i><%# end %>-->
            <%= link_to '<i class="bi bi-trash" style="color:red;" title="DELETE">DELETE</i>'.html_safe, flight, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>



<%= raw pagy_nav(@pagy) %>

</div>


<br>

<%= link_to 'New Flight', new_flight_path %>

<style>
    .pagination {
        display: block;
    }
</style>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1 style="text-align: center; font-weight: bold">Flight Informations</h1>
</div>


<div class="row" style="text-align: center; margin-top: 40px">
  <div class="col-sm">
    <p class="dot">
      <span><%= @flight.number %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span><%= @flight.departure_airport %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span><%= @flight.arrival_airport %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span><%= @flight.business_class_seats %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span><%= @flight.economy_class_seats %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span> <%= @flight.duration %> minutes</span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span>  <%= @flight.departure_date.strftime("%d/%m/%Y à %H:%M") %></span>
    </p>
  </div>
  <div class="col-sm">
    <p class="dot">
      <span> <%= (@flight.departure_date + @flight.duration*60).strftime("%d/%m/%Y à %H:%M") %></span>
    </p>
  </div>
</div>


<div class="row" style="text-align: center">
  <div class="col-sm">
    <strong>Number</strong>
  </div>
  <div class="col-sm">
    <strong>Departure airport</strong>
  </div>
  <div class="col-sm">
    <strong>Arrival airport</strong>
  </div>
  <div class="col-sm">
    <strong>Business class seats</strong>
  </div>
  <div class="col-sm">
    <strong>Economy class seats</strong>
  </div>
  <div class="col-sm">
    <strong>Duration</strong>
  </div>
  <div class="col-sm">
    <strong>Departure date</strong>
  </div>
  <div class="col-sm">
    <strong>Arrival date</strong>
  </div>

</div>


<div style="text-align: center; margin-top: 50px">
  <%= link_to '<span style="color:white;">Edit <i class="bi bi-pencil"></i></span>'.html_safe, edit_flight_path(@flight), class: "btn btn-info" %>
  <%= link_to '<span style="color:white;">Home <i class="bi bi-house"></i> </span>'.html_safe, flights_path,class: "btn btn-dark" %>

  <% if user_signed_in? %>
    <%= link_to 'Reserve', new_reservation_path(flight_id: @flight.id), class: "btn btn-info" %>
  <% end  %>
</div>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Dear Stranger' %>

<h1>Welcome, <%= name %></h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aviation2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render 'shared/navbar' %>
  <%= yield %>

  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :class_seats %>
    <select name="reservation[class_seats]" id="reservation_class_seats">
      <option value="business">business</option>
      <option value="economy">economy</option>
    </select>
  </div>


  <input type="hidden" class="form-control col-md-4 offset-md-4" value="<%= rand(111111..999999) + current_user.id + @flight.id %>" style="text-align: center" type="text" name="reservation[code_reservation]" id="reservation_code_reservation">
  <input type="hidden" name="reservation[user_id]" id="reservation_user_id" value="<%= current_user.id %>" />
  <input type="hidden" name="reservation[flight_id]" id="reservation_flight_id" value="<%= @flight.id %>">

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<div class="table-responsive">
  <table class="table" style="text-align: center">
  <thead>
    <tr>
      <th>Class seats</th>
      <th>Num Avion</th>
      <th>Code Reservation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.class_seats %></td>
        <td><%= reservation.flight_id %></td>
        <td><%= reservation.code_reservation %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Class seats:</strong>
  <%= @reservation.class_seats %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">SuperAirFlight</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to 'Flight', flights_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Your flight', reservations_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end  %>


    </ul>
  </div>
</nav>